import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by MSW (not our source):
    "public/mockServiceWorker.js",
    // Generated from the backend OpenAPI document:
    "src/lib/api/generated/**",
  ]),
  {
    rules: {
      "no-console": "error",
    },
  },
  {
    files: ["src/lib/observability/logger.ts", "scripts/**/*.mjs"],
    rules: {
      "no-console": "off",
    },
  },
]);

export default eslintConfig;
